services:
  db:
    image: postgres:16-alpine
    container_name: voice_assistant_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: voice_assistant
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    volumes:
      - voice_assistant_postgres_data:/var/lib/postgresql/data

volumes:
  voice_assistant_postgres_data:
